; PlatformIO Configuration for Self-Balancing Motorcycle
; Arduino Engineering Kit Rev2 - Arduino Nano 33 IoT + Nano Motor Carrier

[env:nano33iot]
platform = atmelsam
board = nano_33_iot
framework = arduino

; Serial monitor
monitor_speed = 115200

; Libraries
lib_deps =
    arduino-libraries/ArduinoMotorCarrier@^2.0.0
    arduino-libraries/Arduino_LSM6DS3@^1.0.2
    jandrassy/ArduinoOTA@^1.1.1
    arduino-libraries/WiFiNINA@^1.8.14

; Build flags
build_flags =
    -DARDUINO_SAMD_NANO_33_IOT
    -Wall

; --- OTA Upload Configuration ---
upload_protocol = custom
upload_port = 192.168.137.86
extra_scripts = ota_upload.py
custom_ota_password = password
custom_ota_port = 65280
custom_ota_monitor_port = 65281
